alias apt-proxy-on="sudo mv /etc/apt/apt.conf.d/proxy.conf.bak /etc/apt/apt.conf.d/proxy.conf"
alias apt-proxy-off="sudo mv /etc/apt/apt.conf.d/proxy.conf /etc/apt/apt.conf.d/proxy.conf.bak"
alias apt-proxy-status="cat /etc/apt/apt.conf.d/proxy.conf"
alias kvm-rmmod="sudo rmmod kvm_amd kvm"
alias kvm-modprobe="sudo modprobe kvm kvm_amd"
alias F='gsettings set org.gnome.system.proxy mode manual'
alias FF='gsettings set org.gnome.system.proxy mode none'
alias FS='gsettings get org.gnome.system.proxy mode'
alias jumpstat='autojump -s'
